steps:
  # ── Build container image ────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/eisen-auth:$SHORT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/eisen-auth:latest"
      - "."

  # ── Push to Container Registry ───────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/eisen-auth:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/eisen-auth:latest"

  # ── Deploy to Cloud Run ──────────────────────────────
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "eisen-auth"
      - "--image=gcr.io/$PROJECT_ID/eisen-auth:$SHORT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--cpu=1"
      - "--memory=512Mi"
      - "--min-instances=0"
      - "--max-instances=10"
      - "--concurrency=80"
      - "--timeout=30s"
      - "--set-secrets"
      - >-
        DATABASE_URL=DATABASE_URL:latest,
        JWT_SECRET=JWT_SECRET:latest,
        MASTER_KEY_CIPHERTEXT=MASTER_KEY_CIPHERTEXT:latest,
        GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,
        GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,
        GITHUB_CLIENT_ID=GITHUB_CLIENT_ID:latest,
        GITHUB_CLIENT_SECRET=GITHUB_CLIENT_SECRET:latest,
        STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,
        STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,
        ADMIN_SECRET=ADMIN_SECRET:latest
      - "--set-env-vars"
      - >-
        NODE_ENV=production,
        ALLOWED_ORIGINS=https://eisenlabs.com,
        FRONTEND_URL=https://eisenlabs.com,
        PUBLIC_URL=https://api.eisenlabs.com,
        GOOGLE_REDIRECT_URI=https://api.eisenlabs.com/auth/google/callback,
        GITHUB_REDIRECT_URI=https://api.eisenlabs.com/auth/github/callback,
        GCP_PROJECT_ID=$PROJECT_ID,
        GCP_KMS_LOCATION=global,
        GCP_KMS_KEY_RING=eisen-auth,
        GCP_KMS_KEY_NAME=master-key,
        STRIPE_PRO_PRICE_ID=price_pro_placeholder,
        STRIPE_PREMIUM_PRICE_ID=price_premium_placeholder

images:
  - "gcr.io/$PROJECT_ID/eisen-auth:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/eisen-auth:latest"

options:
  logging: CLOUD_LOGGING_ONLY
